version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'chinese-christian.jp -> http://host.docker.internal:5000'
      # STAGE: 'production'
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    networks:
      - app_net
  web:
    build: web
    container_name: web_server
    ports:
      - "5000:5000"
    tty: yes
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      FLASK_ENV: "produciton"
      # FLASK_ENV: "development"
    depends_on:  # api1サーバーはdbサーバーが立ってから起動
      - db
    volumes:
      - ./web/script:/work/mysql_flask/script/
    networks:  # api1とdbを接続するための共通ネットワーク指定
      - app_net
    # command: flask run --host 0.0.0.0 --port 5000
  db:
    build: mysql
    container_name: db_server
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: attendance
      TZ: Asia/Tokyo
    volumes:
      - ./db-data:/var/lib/mysql
    command: mysqld
    networks:
      - app_net
volumes:
  db-data:
networks:
  app_net:
    driver: bridge
