version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: '${DOMAIN} -> http://web_server:5000'
      STAGE: '${STAGE}'
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    networks:
      - app_net
  web:
    build: web
    container_name: web_server
    ports:
      - "5000:5000"
    tty: yes
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      ENV_FILE_NAME: ".env"
      FLASK_ENV: "${FLASK_ENV}"
      GMAIL_HOST: "${GMAIL_HOST}"
      GMAIL_USER: "${GMAIL_USER}"
      GMAIL_PASS: "${GMAIL_PASS}"
    depends_on:  # api1サーバーはdbサーバーが立ってから起動
      - db
    volumes:
      - ./web/django:/work/mysql_flask/django/
    networks:  # api1とdbを接続するための共通ネットワーク指定
      - app_net
    # command: flask run --host 0.0.0.0 --port 5000
  db:
    build: mysql
    container_name: db_server
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      TZ: Asia/Tokyo
    volumes:
      - ./db-data:/var/lib/mysql
    command: mysqld
    networks:
      - app_net
volumes:
  db-data:
networks:
  app_net:
    driver: bridge
